# Generated by Django 4.2.7 on 2025-09-05 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_chatbot_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrime',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for the crime post', null=True, upload_to='crime_banners/'),
        ),
    ]
