# Generated by Django 4.2.7 on 2025-09-05 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_image_fields_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrime',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Additional image 1 (infographic, etc.)', null=True, upload_to='crime_images/'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Additional image 2 (infographic, etc.)', null=True, upload_to='crime_images/'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Additional image 3 (infographic, etc.)', null=True, upload_to='crime_images/'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Additional image 4 (infographic, etc.)', null=True, upload_to='crime_images/'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Additional image 5 (infographic, etc.)', null=True, upload_to='crime_images/'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='image_6',
            field=models.ImageField(blank=True, help_text='Additional image 6 (infographic, etc.)', null=True, upload_to='crime_images/'),
        ),
    ]
