# Generated by Django 4.2.7 on 2025-12-07 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_individual_image_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tips',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_steps',
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tip_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tip_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tip_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tip_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_step_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_step_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_step_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_step_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
