# Generated by Django 4.2.7 on 2026-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_cybercrime_prevention_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrime',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Explanation of how the crime is executed', null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='impact',
            field=models.TextField(blank=True, help_text='Bullet points describing the impact', null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='solution',
            field=models.TextField(blank=True, help_text='Steps for solution and next steps', null=True),
        ),
    ]
