# Generated by Django 4.2.7 on 2026-01-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cybercrime_how_it_works_cybercrime_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercrime',
            name='category',
            field=models.CharField(choices=[('csam', 'Child Pornography/ Child sexually abusive material (CSAM)'), ('cyber_bullying', 'Cyber Bullying'), ('cyber_stalking', 'Cyber stalking'), ('cyber_grooming', 'Cyber Grooming'), ('job_fraud', 'Online Job Fraud'), ('online_sextortion', 'Online Sextortion'), ('vishing', 'Vishing'), ('sexting', 'Sexting'), ('smshing', 'Smshing'), ('sim_swap', 'SIM Swap Scam'), ('card_fraud', 'Debit/Credit Card Fraud'), ('identity_theft', 'Impersonation and Identity Theft'), ('phishing', 'Phishing'), ('spamming', 'Spamming'), ('ransomware', 'Ransomware'), ('malware', 'Virus, Worms & Trojans'), ('data_breach', 'Data Breach'), ('dos_ddos', 'Denial Of Services /Distributed DoS'), ('website_defacement', 'Website Defacement'), ('cyber_squatting', 'Cyber-Squatting'), ('pharming', 'Pharming'), ('cryptojacking', 'Cryptojacking'), ('drug_trafficking', 'Online Drug Trafficking'), ('espionage', 'Espionage')], max_length=50),
        ),
    ]
