# Generated by Django 4.2.7 on 2026-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cybercrime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercrime',
            name='how_it_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cybercrime',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cybercrime',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
