# Generated by Django 4.2.7 on 2026-05-08 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cybercrime_how_it_works_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed Login Attempt'), ('RATE_LIMIT', 'Rate Limit Triggered'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('INVALID_TOKEN', 'Invalid Token Usage')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
