# Generated by Django 4.2.7 on 2026-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cybercrime_how_it_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotconfig',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
    ]
