# Generated by Django 4.2.7 on 2026-05-12 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_chatbotconfig_gemini_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('passwords', 'Passwords & Authentication'), ('social_media', 'Social Media Safety'), ('financial', 'Financial Security'), ('phishing', 'Phishing & Scams'), ('general', 'General Hygiene')], max_length=50)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_questions',
            },
        ),
        migrations.CreateModel(
            name='SecurityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Anonymous session ID for non-logged-in users', max_length=100)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('results_json', models.JSONField(default=dict, help_text='Detailed answers for report generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySafetyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('total_reports_filed', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('avg_assessment_score', models.FloatField(default=0.0)),
                ('safety_index', models.IntegerField(default=0, help_text='Calculated safety index 0-100')),
                ('top_threat_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monthly_safety_scores',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
