# Generated by Django 4.2.7 on 2026-05-08 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_securityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_check', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_uptime',
            },
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='username',
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('failed_login', 'Failed Login Attempt'), ('rate_limit', 'Rate Limit Triggered'), ('suspicious_activity', 'Suspicious Activity'), ('invalid_token', 'Invalid Token Attempt'), ('unauthorized_access', 'Unauthorized Access Attempt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
