# Generated by Django 4.2.7 on 2026-05-15 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_systemuptime_remove_securityevent_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unique_visitors',
            },
        ),
    ]
