# Generated by Django 4.2.7 on 2026-05-16 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_uniquevisitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cybercrime',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tip_1',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tip_2',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tip_3',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tip_4',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tip_5',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='prevention_tip_6',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_step_1',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_step_2',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_step_3',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_step_4',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_step_5',
        ),
        migrations.RemoveField(
            model_name='cybercrime',
            name='reporting_step_6',
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tips',
            field=models.JSONField(blank=True, default=list, help_text='List of prevention tips'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of reporting steps'),
        ),
        migrations.CreateModel(
            name='CyberCrimeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='crime_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='main.cybercrime')),
            ],
            options={
                'db_table': 'cybercrime_images',
                'ordering': ['created_at'],
            },
        ),
    ]
