# Generated by Django 6.0.5 on 2026-05-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_cybercrime_image_1_remove_cybercrime_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
