# Generated by Django 6.0.5 on 2026-05-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_adminuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='gemini_api_key',
        ),
    ]
