# Generated by Django 6.0.5 on 2026-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_chatbotconfig_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrime',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of keywords for semantic search'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='related_domains',
            field=models.JSONField(blank=True, default=list, help_text='List of related domains associated with the threat'),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of short display tags'),
        ),
    ]
