# Generated by Django 6.0.5 on 2026-05-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_assessmentquestion_securityassessment_and_more'),
        ('main', '0017_cybercrime_keywords_cybercrime_related_domains_and_more'),
    ]

    operations = [
    ]
