# Generated by Django 6.0.5 on 2026-06-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_merge_20260526_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='MonthlySafetyScore',
        ),
        migrations.DeleteModel(
            name='SecurityAssessment',
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='gemini_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='system_prompt',
            field=models.TextField(default='You are a cybersecurity assistant focused on online safety, fraud prevention, cybercrime awareness, and digital protection.'),
        ),
    ]
