# Generated by Django 6.0.5 on 2026-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_assessmentquestion_delete_monthlysafetyscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('phishing', 'Phishing & Scams'), ('passwords', 'Password Security'), ('social_media', 'Social Media Privacy'), ('malware', 'Malware & Devices'), ('general', 'General Security')], default='general', max_length=50)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='uniquevisitor',
            options={'verbose_name': 'Unique Visitor', 'verbose_name_plural': 'Unique Visitors'},
        ),
        migrations.AlterModelTable(
            name='uniquevisitor',
            table=None,
        ),
    ]
