# Generated by Django 6.0.5 on 2026-06-20 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_securityquestion_alter_uniquevisitor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('category_scores', models.JSONField(default=dict)),
                ('weaknesses', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='uniquevisitor',
            options={},
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='category',
            field=models.CharField(choices=[('password_security', 'Password Security'), ('phishing', 'Phishing & Scams'), ('social_engineering', 'Social Engineering'), ('mobile_security', 'Mobile Security'), ('banking_fraud', 'Banking Fraud'), ('privacy_protection', 'Privacy Protection'), ('public_wifi', 'Public WiFi'), ('upi_scams', 'UPI Scams'), ('device_security', 'Device Security'), ('safe_browsing', 'Safe Browsing')], default='phishing', max_length=50),
        ),
        migrations.AlterModelTable(
            name='uniquevisitor',
            table='unique_visitors',
        ),
    ]
